### ISSUE TITLE
Allow Return Character Notes Field

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_iOS#28]
The user should be able to format the notes field and hit the return key to move to next line or multiple lines.

**Comment by agildehaus** [comment]
Added in d17f00492734d14e7804487bca8233f1e766d2fc.

**Comment by bravozulu1** [comment]
The return characters appear to be working on iOS.  I am not seeing them on the Mac client.

Are you sure they are not being stripped out?

![passwords_-_passwordvault_and_add_delete_confirmation_dialog_ _issue__33_ _blustor_passwordvault_ios](https://user-images.githubusercontent.com/10087224/29221997-59cb5dc6-7e86-11e7-942d-1e65f76f232e.jpg)
