### ISSUE TITLE
Edit Entry

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_iOS#32]
Edit entry bottom menu when editing an entry.... says "Group" instead of "Entry".   Minor text change.

![img_9870](https://user-images.githubusercontent.com/10087224/28745699-2fac00a6-7443-11e7-9c53-0482d3b5f800.PNG)

**Comment by agildehaus** [comment]
Fixed in 4bf3a1ba742b8068d78454f79d4cd2cd68bcf2ab.
