### ISSUE TITLE
Card Wake Fails

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_iOS#35]
When the card goes to sleep, it takes two retries to get it to wake up.   We have resolved this issue by re-trying when the connection fails on Mac and Windows.  Since it could fail for multiple reasons.  i.e. weak signal or the card is asleep and just woke up.

Can we try to connect multiple times?   I've seen this issue with opening an existing database.  It takes multiple attempts.   Change the application to try multiple times to connect and complete operation.

**Comment by agildehaus** [comment]
Will retry twice as of 08114217db1307217684059ee4f60d674627cc29.
